version: '3'
services:
  backend:
    image: tea-backend
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html