version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tea-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    restart: unless-stopped